repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflicts

-   repo: https://github.com/pre-commit/mirrors-csslint
    rev:  ''
    hooks:
    -   id: csslint

-   repo: https://github.com/Lucas-C/pre-commit-hooks-java 
    rev: ''
    hooks:
    -   id: validate-html

-   repo: https://github.com/jorisroovers/gitlint 
    rev: ''
    hooks:
    -   id: gitlint